// Testimonial data model and sample data for the testimonials page

const testimonials = [
  {
    id: "1",
    name: "Jane Doe",
    discordUsername: "JaneDoe#1234",
    community: "BaldApe's Lab",
    role: "Member",
    rating: 5,
    featuresLiked: ["Organization", "Community", "Support"],
    text: "This server is amazing! The organization and support are top-notch.",
    permission: "public",
    date: "2024-06-01",
    source: "form",
  },
  {
    id: "2",
    name: "Anonymous",
    discordUsername: null,
    community: "Panda Picks",
    role: "VIP",
    rating: 4,
    featuresLiked: ["Channel Structure", "Picks Accuracy"],
    text: "Love the picks and the clean channel layout. Would recommend!",
    permission: "public",
    date: "2024-05-28",
    source: "discord",
  },
  {
    id: "3",
    name: "Jacob S.",
    discordUsername: "SportsSciJacob#5678",
    community: "SportsSciJacob",
    role: "Moderator",
    rating: 5,
    featuresLiked: ["Data Analysis", "Professionalism"],
    text: "Professional setup and great data-driven discussions.",
    permission: "public",
    date: "2024-05-20",
    source: "manual",
  },
  {
    id: "4",
    name: "Raven",
    discordUsername: "BetsByRaven#9999",
    community: "BetsByRaven",
    role: "Owner",
    rating: 5,
    featuresLiked: ["Specialized Features", "Community"],
    text: "Specialized features for WNBA fans. The community is awesome!",
    permission: "public",
    date: "2024-05-15",
    source: "form",
  },
  {
    id: "5",
    name: "Anonymous",
    discordUsername: null,
    community: "Cloak Line Bets",
    role: "Member",
    rating: 3,
    featuresLiked: ["Analytics"],
    text: "Analytics are good, but would love more engagement events.",
    permission: "public",
    date: "2024-05-10",
    source: "form",
  },
];

export default testimonials; 